version: '3.8'
services:
  main:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./dbstorage:/data/db
    container_name: mongo